/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export declare namespace IMarketplace {
  export type CounterofferStruct = {
    collection: PromiseOrValue<string>;
    nftId: PromiseOrValue<BigNumberish>;
    offerId: PromiseOrValue<BigNumberish>;
    price: PromiseOrValue<BigNumberish>;
    expirationDate: PromiseOrValue<BigNumberish>;
  };

  export type CounterofferStructOutput = [
    string,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber
  ] & {
    collection: string;
    nftId: BigNumber;
    offerId: BigNumber;
    price: BigNumber;
    expirationDate: BigNumber;
  };

  export type NftInfoStruct = {
    listed: PromiseOrValue<boolean>;
    price: PromiseOrValue<BigNumberish>;
    seller: PromiseOrValue<string>;
    totalOffers: PromiseOrValue<BigNumberish>;
  };

  export type NftInfoStructOutput = [boolean, BigNumber, string, BigNumber] & {
    listed: boolean;
    price: BigNumber;
    seller: string;
    totalOffers: BigNumber;
  };

  export type OfferStruct = {
    isInitialized: PromiseOrValue<boolean>;
    buyer: PromiseOrValue<string>;
    price: PromiseOrValue<BigNumberish>;
    expirationDate: PromiseOrValue<BigNumberish>;
    counterofferId: PromiseOrValue<BigNumberish>;
  };

  export type OfferStructOutput = [
    boolean,
    string,
    BigNumber,
    BigNumber,
    BigNumber
  ] & {
    isInitialized: boolean;
    buyer: string;
    price: BigNumber;
    expirationDate: BigNumber;
    counterofferId: BigNumber;
  };
}

export interface IMsgValuePaymentMarketplaceInterface extends utils.Interface {
  functions: {
    "buy(address,uint256)": FunctionFragment;
    "cancelOffer(address,uint256,uint256)": FunctionFragment;
    "changePriceOf(address,uint256,uint256)": FunctionFragment;
    "feeRatio()": FunctionFragment;
    "floorRatio()": FunctionFragment;
    "fusyBenefitsAccumulated()": FunctionFragment;
    "getCounteroffer(uint256)": FunctionFragment;
    "getCounteroffer(address,uint256,uint256)": FunctionFragment;
    "getFusyonaFeeFor(uint256)": FunctionFragment;
    "getNftInfo(address,uint256)": FunctionFragment;
    "getOffer(address,uint256,uint256)": FunctionFragment;
    "isListed(address,uint256)": FunctionFragment;
    "list(address,uint256,uint256)": FunctionFragment;
    "makeCounteroffer(address,uint256,uint256,uint256,uint64)": FunctionFragment;
    "makeOffer(address,uint256,uint64)": FunctionFragment;
    "setFeeRatioFromPercentage(uint8)": FunctionFragment;
    "setFloorRatioFromPercentage(uint8)": FunctionFragment;
    "takeCounteroffer(uint256)": FunctionFragment;
    "takeOffer(address,uint256,uint256)": FunctionFragment;
    "withdraw()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "buy"
      | "cancelOffer"
      | "changePriceOf"
      | "feeRatio"
      | "floorRatio"
      | "fusyBenefitsAccumulated"
      | "getCounteroffer(uint256)"
      | "getCounteroffer(address,uint256,uint256)"
      | "getFusyonaFeeFor"
      | "getNftInfo"
      | "getOffer"
      | "isListed"
      | "list"
      | "makeCounteroffer"
      | "makeOffer"
      | "setFeeRatioFromPercentage"
      | "setFloorRatioFromPercentage"
      | "takeCounteroffer"
      | "takeOffer"
      | "withdraw"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "buy",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelOffer",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "changePriceOf",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(functionFragment: "feeRatio", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "floorRatio",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "fusyBenefitsAccumulated",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCounteroffer(uint256)",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getCounteroffer(address,uint256,uint256)",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getFusyonaFeeFor",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getNftInfo",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getOffer",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "isListed",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "list",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "makeCounteroffer",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "makeOffer",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeRatioFromPercentage",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setFloorRatioFromPercentage",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "takeCounteroffer",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "takeOffer",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(functionFragment: "withdraw", values?: undefined): string;

  decodeFunctionResult(functionFragment: "buy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cancelOffer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "changePriceOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "feeRatio", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "floorRatio", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "fusyBenefitsAccumulated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCounteroffer(uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCounteroffer(address,uint256,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFusyonaFeeFor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getNftInfo", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getOffer", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isListed", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "list", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "makeCounteroffer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "makeOffer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setFeeRatioFromPercentage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFloorRatioFromPercentage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "takeCounteroffer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "takeOffer", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;

  events: {
    "CancelledOffer(address,uint256,uint256,uint256,address)": EventFragment;
    "CounterofferMade(address,uint256,uint256,uint256)": EventFragment;
    "CounterofferTaken(uint256,uint256,address)": EventFragment;
    "NFTListed(address,address,uint256,uint256)": EventFragment;
    "NFTPriceChanged(address,uint256,uint256)": EventFragment;
    "NFTSold(address,address,address,uint256,uint256)": EventFragment;
    "OfferMade(address,address,uint256,uint256)": EventFragment;
    "RootWithdrawal(address,uint256)": EventFragment;
    "RoyaltyPayment(address,uint256,address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "CancelledOffer"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CounterofferMade"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CounterofferTaken"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NFTListed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NFTPriceChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NFTSold"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OfferMade"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RootWithdrawal"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoyaltyPayment"): EventFragment;
}

export interface CancelledOfferEventObject {
  collection: string;
  tokenId: BigNumber;
  indexOfOfferMapping: BigNumber;
  priceOffer: BigNumber;
  buyer: string;
}
export type CancelledOfferEvent = TypedEvent<
  [string, BigNumber, BigNumber, BigNumber, string],
  CancelledOfferEventObject
>;

export type CancelledOfferEventFilter = TypedEventFilter<CancelledOfferEvent>;

export interface CounterofferMadeEventObject {
  collection: string;
  nftId: BigNumber;
  offerId: BigNumber;
  counterofferId: BigNumber;
}
export type CounterofferMadeEvent = TypedEvent<
  [string, BigNumber, BigNumber, BigNumber],
  CounterofferMadeEventObject
>;

export type CounterofferMadeEventFilter =
  TypedEventFilter<CounterofferMadeEvent>;

export interface CounterofferTakenEventObject {
  id: BigNumber;
  price: BigNumber;
  seller: string;
}
export type CounterofferTakenEvent = TypedEvent<
  [BigNumber, BigNumber, string],
  CounterofferTakenEventObject
>;

export type CounterofferTakenEventFilter =
  TypedEventFilter<CounterofferTakenEvent>;

export interface NFTListedEventObject {
  seller: string;
  collection: string;
  nftId: BigNumber;
  price: BigNumber;
}
export type NFTListedEvent = TypedEvent<
  [string, string, BigNumber, BigNumber],
  NFTListedEventObject
>;

export type NFTListedEventFilter = TypedEventFilter<NFTListedEvent>;

export interface NFTPriceChangedEventObject {
  collection: string;
  nftId: BigNumber;
  newPrice: BigNumber;
}
export type NFTPriceChangedEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  NFTPriceChangedEventObject
>;

export type NFTPriceChangedEventFilter = TypedEventFilter<NFTPriceChangedEvent>;

export interface NFTSoldEventObject {
  buyer: string;
  seller: string;
  collection: string;
  nftId: BigNumber;
  price: BigNumber;
}
export type NFTSoldEvent = TypedEvent<
  [string, string, string, BigNumber, BigNumber],
  NFTSoldEventObject
>;

export type NFTSoldEventFilter = TypedEventFilter<NFTSoldEvent>;

export interface OfferMadeEventObject {
  buyer: string;
  collection: string;
  nftId: BigNumber;
  offerId: BigNumber;
}
export type OfferMadeEvent = TypedEvent<
  [string, string, BigNumber, BigNumber],
  OfferMadeEventObject
>;

export type OfferMadeEventFilter = TypedEventFilter<OfferMadeEvent>;

export interface RootWithdrawalEventObject {
  beneficiary: string;
  amount: BigNumber;
}
export type RootWithdrawalEvent = TypedEvent<
  [string, BigNumber],
  RootWithdrawalEventObject
>;

export type RootWithdrawalEventFilter = TypedEventFilter<RootWithdrawalEvent>;

export interface RoyaltyPaymentEventObject {
  collection: string;
  tokenId: BigNumber;
  beneficiary: string;
  royalty: BigNumber;
}
export type RoyaltyPaymentEvent = TypedEvent<
  [string, BigNumber, string, BigNumber],
  RoyaltyPaymentEventObject
>;

export type RoyaltyPaymentEventFilter = TypedEventFilter<RoyaltyPaymentEvent>;

export interface IMsgValuePaymentMarketplace extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IMsgValuePaymentMarketplaceInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    buy(
      collection: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    cancelOffer(
      collection: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      indexOfOfferMapping: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    changePriceOf(
      collection: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      newPrice: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    feeRatio(overrides?: CallOverrides): Promise<[BigNumber]>;

    floorRatio(overrides?: CallOverrides): Promise<[BigNumber]>;

    fusyBenefitsAccumulated(overrides?: CallOverrides): Promise<[BigNumber]>;

    "getCounteroffer(uint256)"(
      counterofferId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[IMarketplace.CounterofferStructOutput]>;

    "getCounteroffer(address,uint256,uint256)"(
      collection: PromiseOrValue<string>,
      nftId: PromiseOrValue<BigNumberish>,
      offerId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[IMarketplace.CounterofferStructOutput]>;

    getFusyonaFeeFor(
      price: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getNftInfo(
      collection: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[IMarketplace.NftInfoStructOutput]>;

    getOffer(
      collection: PromiseOrValue<string>,
      nftId: PromiseOrValue<BigNumberish>,
      offerId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[IMarketplace.OfferStructOutput]>;

    isListed(
      collection: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    list(
      collection: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      price: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    makeCounteroffer(
      collection: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      offerId: PromiseOrValue<BigNumberish>,
      newPriceOffer: PromiseOrValue<BigNumberish>,
      durationInDays: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    makeOffer(
      collection: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      durationInDays: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setFeeRatioFromPercentage(
      percentage: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setFloorRatioFromPercentage(
      percentage: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    takeCounteroffer(
      id: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    takeOffer(
      collection: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      indexOfOfferMapping: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    withdraw(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  buy(
    collection: PromiseOrValue<string>,
    tokenId: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  cancelOffer(
    collection: PromiseOrValue<string>,
    tokenId: PromiseOrValue<BigNumberish>,
    indexOfOfferMapping: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  changePriceOf(
    collection: PromiseOrValue<string>,
    tokenId: PromiseOrValue<BigNumberish>,
    newPrice: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  feeRatio(overrides?: CallOverrides): Promise<BigNumber>;

  floorRatio(overrides?: CallOverrides): Promise<BigNumber>;

  fusyBenefitsAccumulated(overrides?: CallOverrides): Promise<BigNumber>;

  "getCounteroffer(uint256)"(
    counterofferId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<IMarketplace.CounterofferStructOutput>;

  "getCounteroffer(address,uint256,uint256)"(
    collection: PromiseOrValue<string>,
    nftId: PromiseOrValue<BigNumberish>,
    offerId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<IMarketplace.CounterofferStructOutput>;

  getFusyonaFeeFor(
    price: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getNftInfo(
    collection: PromiseOrValue<string>,
    tokenId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<IMarketplace.NftInfoStructOutput>;

  getOffer(
    collection: PromiseOrValue<string>,
    nftId: PromiseOrValue<BigNumberish>,
    offerId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<IMarketplace.OfferStructOutput>;

  isListed(
    collection: PromiseOrValue<string>,
    tokenId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  list(
    collection: PromiseOrValue<string>,
    tokenId: PromiseOrValue<BigNumberish>,
    price: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  makeCounteroffer(
    collection: PromiseOrValue<string>,
    tokenId: PromiseOrValue<BigNumberish>,
    offerId: PromiseOrValue<BigNumberish>,
    newPriceOffer: PromiseOrValue<BigNumberish>,
    durationInDays: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  makeOffer(
    collection: PromiseOrValue<string>,
    tokenId: PromiseOrValue<BigNumberish>,
    durationInDays: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setFeeRatioFromPercentage(
    percentage: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setFloorRatioFromPercentage(
    percentage: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  takeCounteroffer(
    id: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  takeOffer(
    collection: PromiseOrValue<string>,
    tokenId: PromiseOrValue<BigNumberish>,
    indexOfOfferMapping: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  withdraw(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    buy(
      collection: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    cancelOffer(
      collection: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      indexOfOfferMapping: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    changePriceOf(
      collection: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      newPrice: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    feeRatio(overrides?: CallOverrides): Promise<BigNumber>;

    floorRatio(overrides?: CallOverrides): Promise<BigNumber>;

    fusyBenefitsAccumulated(overrides?: CallOverrides): Promise<BigNumber>;

    "getCounteroffer(uint256)"(
      counterofferId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<IMarketplace.CounterofferStructOutput>;

    "getCounteroffer(address,uint256,uint256)"(
      collection: PromiseOrValue<string>,
      nftId: PromiseOrValue<BigNumberish>,
      offerId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<IMarketplace.CounterofferStructOutput>;

    getFusyonaFeeFor(
      price: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getNftInfo(
      collection: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<IMarketplace.NftInfoStructOutput>;

    getOffer(
      collection: PromiseOrValue<string>,
      nftId: PromiseOrValue<BigNumberish>,
      offerId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<IMarketplace.OfferStructOutput>;

    isListed(
      collection: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    list(
      collection: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      price: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    makeCounteroffer(
      collection: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      offerId: PromiseOrValue<BigNumberish>,
      newPriceOffer: PromiseOrValue<BigNumberish>,
      durationInDays: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    makeOffer(
      collection: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      durationInDays: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setFeeRatioFromPercentage(
      percentage: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setFloorRatioFromPercentage(
      percentage: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    takeCounteroffer(
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    takeOffer(
      collection: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      indexOfOfferMapping: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    withdraw(overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    "CancelledOffer(address,uint256,uint256,uint256,address)"(
      collection?: PromiseOrValue<string> | null,
      tokenId?: PromiseOrValue<BigNumberish> | null,
      indexOfOfferMapping?: null,
      priceOffer?: null,
      buyer?: PromiseOrValue<string> | null
    ): CancelledOfferEventFilter;
    CancelledOffer(
      collection?: PromiseOrValue<string> | null,
      tokenId?: PromiseOrValue<BigNumberish> | null,
      indexOfOfferMapping?: null,
      priceOffer?: null,
      buyer?: PromiseOrValue<string> | null
    ): CancelledOfferEventFilter;

    "CounterofferMade(address,uint256,uint256,uint256)"(
      collection?: PromiseOrValue<string> | null,
      nftId?: PromiseOrValue<BigNumberish> | null,
      offerId?: PromiseOrValue<BigNumberish> | null,
      counterofferId?: null
    ): CounterofferMadeEventFilter;
    CounterofferMade(
      collection?: PromiseOrValue<string> | null,
      nftId?: PromiseOrValue<BigNumberish> | null,
      offerId?: PromiseOrValue<BigNumberish> | null,
      counterofferId?: null
    ): CounterofferMadeEventFilter;

    "CounterofferTaken(uint256,uint256,address)"(
      id?: PromiseOrValue<BigNumberish> | null,
      price?: null,
      seller?: PromiseOrValue<string> | null
    ): CounterofferTakenEventFilter;
    CounterofferTaken(
      id?: PromiseOrValue<BigNumberish> | null,
      price?: null,
      seller?: PromiseOrValue<string> | null
    ): CounterofferTakenEventFilter;

    "NFTListed(address,address,uint256,uint256)"(
      seller?: PromiseOrValue<string> | null,
      collection?: PromiseOrValue<string> | null,
      nftId?: null,
      price?: null
    ): NFTListedEventFilter;
    NFTListed(
      seller?: PromiseOrValue<string> | null,
      collection?: PromiseOrValue<string> | null,
      nftId?: null,
      price?: null
    ): NFTListedEventFilter;

    "NFTPriceChanged(address,uint256,uint256)"(
      collection?: PromiseOrValue<string> | null,
      nftId?: PromiseOrValue<BigNumberish> | null,
      newPrice?: null
    ): NFTPriceChangedEventFilter;
    NFTPriceChanged(
      collection?: PromiseOrValue<string> | null,
      nftId?: PromiseOrValue<BigNumberish> | null,
      newPrice?: null
    ): NFTPriceChangedEventFilter;

    "NFTSold(address,address,address,uint256,uint256)"(
      buyer?: PromiseOrValue<string> | null,
      seller?: PromiseOrValue<string> | null,
      collection?: PromiseOrValue<string> | null,
      nftId?: null,
      price?: null
    ): NFTSoldEventFilter;
    NFTSold(
      buyer?: PromiseOrValue<string> | null,
      seller?: PromiseOrValue<string> | null,
      collection?: PromiseOrValue<string> | null,
      nftId?: null,
      price?: null
    ): NFTSoldEventFilter;

    "OfferMade(address,address,uint256,uint256)"(
      buyer?: PromiseOrValue<string> | null,
      collection?: PromiseOrValue<string> | null,
      nftId?: PromiseOrValue<BigNumberish> | null,
      offerId?: null
    ): OfferMadeEventFilter;
    OfferMade(
      buyer?: PromiseOrValue<string> | null,
      collection?: PromiseOrValue<string> | null,
      nftId?: PromiseOrValue<BigNumberish> | null,
      offerId?: null
    ): OfferMadeEventFilter;

    "RootWithdrawal(address,uint256)"(
      beneficiary?: PromiseOrValue<string> | null,
      amount?: null
    ): RootWithdrawalEventFilter;
    RootWithdrawal(
      beneficiary?: PromiseOrValue<string> | null,
      amount?: null
    ): RootWithdrawalEventFilter;

    "RoyaltyPayment(address,uint256,address,uint256)"(
      collection?: PromiseOrValue<string> | null,
      tokenId?: PromiseOrValue<BigNumberish> | null,
      beneficiary?: PromiseOrValue<string> | null,
      royalty?: null
    ): RoyaltyPaymentEventFilter;
    RoyaltyPayment(
      collection?: PromiseOrValue<string> | null,
      tokenId?: PromiseOrValue<BigNumberish> | null,
      beneficiary?: PromiseOrValue<string> | null,
      royalty?: null
    ): RoyaltyPaymentEventFilter;
  };

  estimateGas: {
    buy(
      collection: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    cancelOffer(
      collection: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      indexOfOfferMapping: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    changePriceOf(
      collection: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      newPrice: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    feeRatio(overrides?: CallOverrides): Promise<BigNumber>;

    floorRatio(overrides?: CallOverrides): Promise<BigNumber>;

    fusyBenefitsAccumulated(overrides?: CallOverrides): Promise<BigNumber>;

    "getCounteroffer(uint256)"(
      counterofferId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getCounteroffer(address,uint256,uint256)"(
      collection: PromiseOrValue<string>,
      nftId: PromiseOrValue<BigNumberish>,
      offerId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getFusyonaFeeFor(
      price: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getNftInfo(
      collection: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getOffer(
      collection: PromiseOrValue<string>,
      nftId: PromiseOrValue<BigNumberish>,
      offerId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isListed(
      collection: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    list(
      collection: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      price: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    makeCounteroffer(
      collection: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      offerId: PromiseOrValue<BigNumberish>,
      newPriceOffer: PromiseOrValue<BigNumberish>,
      durationInDays: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    makeOffer(
      collection: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      durationInDays: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setFeeRatioFromPercentage(
      percentage: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setFloorRatioFromPercentage(
      percentage: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    takeCounteroffer(
      id: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    takeOffer(
      collection: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      indexOfOfferMapping: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    withdraw(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    buy(
      collection: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    cancelOffer(
      collection: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      indexOfOfferMapping: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    changePriceOf(
      collection: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      newPrice: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    feeRatio(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    floorRatio(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    fusyBenefitsAccumulated(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getCounteroffer(uint256)"(
      counterofferId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getCounteroffer(address,uint256,uint256)"(
      collection: PromiseOrValue<string>,
      nftId: PromiseOrValue<BigNumberish>,
      offerId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getFusyonaFeeFor(
      price: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getNftInfo(
      collection: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getOffer(
      collection: PromiseOrValue<string>,
      nftId: PromiseOrValue<BigNumberish>,
      offerId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isListed(
      collection: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    list(
      collection: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      price: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    makeCounteroffer(
      collection: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      offerId: PromiseOrValue<BigNumberish>,
      newPriceOffer: PromiseOrValue<BigNumberish>,
      durationInDays: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    makeOffer(
      collection: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      durationInDays: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setFeeRatioFromPercentage(
      percentage: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setFloorRatioFromPercentage(
      percentage: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    takeCounteroffer(
      id: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    takeOffer(
      collection: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      indexOfOfferMapping: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    withdraw(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
