/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { FusyERC721CollectionWithRoyaltySupport__factory } from "./FusyERC721CollectionWithRoyaltySupport__factory";
